import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SideBar } from "./my-components/sidebar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <SideBar />
          <main className="flex flex-col w-full">
            {children}
        </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
